### ISSUE TITLE
Unrecognized option "parameter_strategy" under "takeit_amp_html.routing"

### ISSUE THREAD

**Issue by marineb** [takeit/AmpHtmlBundle#10]
Hi, 

I picked the parameter strategy. I am getting this error. I may very well be doing other things wrong. 

```
Unrecognized option "parameter_strategy" under "takeit_amp_html.routing"
```

I added that to the `config.yml` file:
```
takeit_amp_html:
    theme:
        current_theme: "amp-theme"
    model: AppBundle\Entity\Article
    routing:
         parameter_strategy:
            enabled: true
```
