### ISSUE TITLE
How can I defined multiple entities to be amp-ified?

### ISSUE THREAD

**Issue by echosa** [takeit/AmpHtmlBundle#9]
Currently, I'm able to get my `Article` entities "amp-ified" like this (after changing the default amp-theme to call the correct getters):

```
takeit_amp_html:
    model: MyBundle\Entity\Article
    routing:
        route_strategy:
            pattern: '{controller}/{action}'
            parameter: 'url'
```

With that, I can go to `/platform/amp/article/view/article-url-goes-here` and see the amp version.

Now, I'd like to also have the same thing for `News` entities. However, I don't see a way to define multiple entities, though. Am I missing something? I'd like something like this or similar:

```
takeit_amp_html:
    entity: 'article'
        model: MyBundle\Entity\Article
        routing:
            route_strategy:
                pattern: '{controller}/{action}'
                parameter: 'url'
        theme:
            current_theme: "article-theme"
    entity: 'news'
        model: MyBundle\Entity\News
        routing:
            route_strategy:
                pattern: '{controller}/{action}'
                parameter: 'url'
        theme:
            current_theme: "news-theme"
```

**Comment by takeit** [comment]
hi @echosa, 
currently, it is not possible to define multiple entities to be amp-ified. I didn't have a use case for this yet. Feel free to contribute tho 😄 

I think there should be only one strategy enabled at the same time to access articles in AMP format. Using [`Route`](https://github.com/takeit/AmpHtmlBundle/blob/master/Resources/doc/index.md#route-strategy) **or** [`Parameter`](https://github.com/takeit/AmpHtmlBundle/blob/master/Resources/doc/index.md#parameter-strategy) strategy.

The config would look like:

```yml
takeit_amp_html:
    routing:
        route_strategy:
            parameter: 'url'
    theme:
        current_theme: "article-theme"
    classes:
        article:
            model: MyBundle\Entity\Article
            route_pattern: '{controller}/{action}' # possible to define its value only when route strategy is enabled
        news:
            model: MyBundle\Entity\News
            route_pattern: '{controller}/{action}' # possible to define its value only when route strategy is enabled
```

You would then, be able to define `route_pattern` for each entity if your urls are different and if [`Route`](https://github.com/takeit/AmpHtmlBundle/blob/master/Resources/doc/index.md#route-strategy) strategy is used. 

You would also have one theme for **all** entities, which should be fine imo. No idea why would you want to have different themes per entity? Is that also your use case? I would love to get more info about it.

This way you would be able to define multiple entities to be amp-ified.

Let me know what do you think about it, or maybe if you have a better idea or if I missed something - I'm open for suggestions 😃
